version: "3.7"
services:
    app:
        build:
            args:
                user: laravel-user
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        container_name: app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - docker-network
    db:
        image: mariadb:10.2
        container_name: database
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./docker/mysql:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
        networks:
            - docker-network
    db_test:
        image: mariadb:10.2
        container_name: database_test
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_TEST_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_TEST_PASSWORD}
            MYSQL_PASSWORD: ${DB_TEST_PASSWORD}
            MYSQL_USER: ${DB_TEST_USERNAME}
        volumes:
            - ./docker/mysql:/docker-entrypoint-initdb.d
        ports:
            - 3307:3307
        networks:
            - docker-network
    nginx:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - docker-network
networks:
  docker-network:
      driver: bridge
